name: Update BITSP Menu JSON

on:
  schedule:
    - cron: "30 15 * * *"

  workflow_dispatch:

jobs:
  update-menu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download JSON
        run: |
          curl -o messmenu.json https://ssmssunoff.vercel.app/messmenu.json

      - name: Check for changes
        id: check
        run: |
          git diff --exit-code || echo "::set-output name=changed::true"

      - name: Commit changes
        if: steps.check.outputs.changed == 'true'
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add messmenu.json
          git commit -m "[refactor] Update menu"
          git push
